# Generated by Django 3.2.5 on 2021-09-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alic', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
